# Generated by Django 5.2.1 on 2025-05-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
