# Generated by Django 5.2.1 on 2025-06-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
